- name: "{{ validator_title }} - digital ocean storage - validate"
  lrd.ext_cloud.vars:
    identifier: "digital_ocean_storage"
    raw_data:
      state: "present"
      namespace: "ext_storage"
      params: "{{ validator_item.data.params | default({}) }}"
      credentials: "{{ validator_item.data.credentials | default({}) }}"
      contents: "{{ validator_item.data.contents | default({}) }}"
  no_log: "{{ env_no_log }}"
