- name: "{{ inner_service_title }} - digital ocean volume - vars"
  lrd.ext_cloud.vars:
    identifier: "digital_ocean_volume"
    raw_data:
      namespace: "ext_volume"
      state: "{{ inner_service_state }}"
      params: "{{ inner_service_params }}"
      credentials: "{{ inner_service_credentials }}"
      contents: "{{ inner_service_contents }}"
  register: ext_volume_data_wrapper
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ inner_service_title }} - digital ocean volume - execute"
  lrd.ext_cloud.digital_ocean_block_storage:
    command: create
    state: "{{ ext_volume_item.state }}"
    oauth_token: "{{ ext_volume_item.api_token }}"
    volume_name: "{{ ext_volume_item.name }}"
    region: "{{ ext_volume_item.region }}"
    block_size: "{{ ext_volume_item.block_size }}"
  loop: "{{ ext_volume_data_wrapper.data.list }}"
  loop_control:
    loop_var: ext_volume_item
    label: "[{{ ext_volume_item.state }}] {{ ext_volume_item.name }}"
  no_log: "{{ env_no_log }}"
