root: "dns_schema"
schemas:
  dns_schema:
    type: "dict"
    description: "aws dns (route53) schema"
    props:
      namespace:
        type: "str"
        non_empty: true
        choices: ["ext_dns"]
      params:
        schema: "params"
        non_empty: true
        description: "aws dns (route53) parameters"
      credentials:
        schema: "credentials"
        non_empty: true
        description: "aws dns (route53) credentials"
  params:
    type: "dict"
    description: "godaddy dns parameters schema"
    props:
      list:
        type: "list"
        elem_schema: "list_item_params"
        description: >-
          list of records to be created/destroyed; used when defined, instead of considering
          the parameters as only one definition; instead, what is defined at the outer parameters
          will be used as a default for each list item parameter; when not defined, will use
          the outer parameters as one single list item
      zone:
        type: "str"
        description: >-
          dns zone/domain (e.g. 'example.com'); the zone must already exist
      dns_type:
        type: "str"
        choices:
          - "A"
          - "AAAA"
          - "CNAME"
          - "DS"
          - "MX"
          - "NS"
          - "SPF"
          - "SRV"
          - "SSHFP"
          - "TLSA"
          - "TXT"
        description: "dns type"
      record:
        type: "str"
        description: "dns record to add/remove (according to state)"
      proxied:
        type: "bool"
        description: "proxy through external network or just use dns"
        choices: [null, false]
      ttl:
        type: "int"
        description: "dns record ttl (time-to-live)"
      weight:
        type: "int"
        description: "dns record weight (for dns_type=SRV)"
      value:
        type: "simple_list"
        elem_type: "str"
        description: "list with strings or a comma-spaced string with the dns record values)"
  list_item_params:
    type: "dict"
    description: "godaddy dns parameters list schema"
    props:
      when:
        type: "bool"
        description: "when false, ignores the item; defaults to true"
      zone:
        type: "str"
        description: >-
          dns zone/domain (e.g. 'example.com'); the zone must already exist
      dns_type:
        type: "str"
        choices:
          - "A"
          - "AAAA"
          - "CNAME"
          - "DS"
          - "MX"
          - "NS"
          - "SPF"
          - "SRV"
          - "SSHFP"
          - "TLSA"
          - "TXT"
        description: "dns type"
      record:
        type: "str"
        description: "dns record to add/remove (according to state)"
      proxied:
        type: "bool"
        description: "proxy through external network or just use dns"
        choices: [null, false]
      ttl:
        type: "int"
        description: "dns record ttl (time-to-live)"
      weight:
        type: "int"
        description: "dns record weight (for dns_type=SRV)"
      value:
        type: "simple_list"
        elem_type: "str"
        description: "list with strings or a comma-spaced string with the dns record values)"
  credentials:
    type: "dict"
    description: "aws dns (route53) credentials schema"
    props:
      dns:
        schema: "aws_credentials"
        non_empty: true
        description: "aws dns (route53) main credentials"
  aws_credentials:
    type: "dict"
    description: "aws dns (route53) main credentials schema"
    props:
      access_key:
        type: "str"
        non_empty: true
        description: "aws access key"
      secret_key:
        type: "str"
        non_empty: true
        description: "aws secret key"
