- name: "{{ inner_service_title }} - aws node - vars"
  lrd.ext_cloud.vars:
    identifier: "aws_node"
    raw_data:
      namespace: "ext_node"
      state: "{{ inner_service_state }}"
      params: "{{ inner_service_params }}"
      credentials: "{{ inner_service_credentials }}"
      contents: "{{ inner_service_contents }}"
  register: ext_node_data_wrapper
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ inner_service_title }} - aws node - execute"
  community.aws.ec2_instance:
    name: "{{ ext_node_item.name }}"
    state: "{{ ext_node_item.state }}"
    access_key: "{{ ext_node_item.access_key }}"
    secret_key: "{{ ext_node_item.secret_key }}"
    image_id: "{{ ext_node_item.image_id }}"
    region: "{{ ext_node_item.region }}"
    instance_type: "{{ ext_node_item.instance_type }}"
    volumes: "{{ ext_node_item.volumes }}"
    vpc_subnet_id: "{{ ext_node_item.vpc_subnet_id | default(omit, true) }}"
    network: "{{ ext_node_item.network | default(omit, true) }}"
    security_groups: "{{ ext_node_item.security_groups | default(omit, true) }}"
    availability_zone: "{{ ext_node_item.availability_zone | default(omit, true) }}"
    cpu_options: "{{ ext_node_item.cpu_options | default(omit, true) }}"
    detailed_monitoring: "{{ ext_node_item.detailed_monitoring | default(omit, true) }}"
    ebs_optimized: "{{ ext_node_item.ebs_optimized | default(omit, true) }}"
    user_data: "{{ ext_node_item.user_data | default(omit, true) }}"
    instance_initiated_shutdown_behavior: >-
      {{ ext_node_item.instance_initiated_shutdown_behavior | default(omit, true) }}
    termination_protection: "{{ ext_node_item.termination_protection | default(omit, true) }}"
    wait_timeout: "{{ ext_node_item.wait_timeout }}"
    wait: true
    purge_tags: true
  loop: "{{ ext_node_data_wrapper.data.replicas }}"
  loop_control:
    loop_var: ext_node_item
    label: "[{{ ext_node_item.state }}] {{ ext_node_item.name }}"
  no_log: "{{ env_no_log }}"

- name: "{{ inner_service_title }} - aws node - set hosts"
  set_fact:
    ext_node_hosts: "{{ ext_node_hosts + [ext_node_item_result] }}"
  vars:
    ext_node_item: "{{ ext_node_item_data.ext_node_item | default({}) }}"
    ext_node_instance: "{{ ext_node_item_data.data.instances[0] | default({}) }}"
    ext_node_item_result:
      name: "{{ ext_node_item.name }}"
      state: "{{ ext_node_item.state }}"
      private_ip: "{{ ext_node_instance.private_ip_address | default('') }}"
      public_ipv4: "{{ ext_node_instance.public_ip_address | default('') }}"
      public_ipv6: "{{ ext_node_instance.network_interfaces[0].ipv6_addresses.ipv6_address | default('') }}"
  loop: "{{ ext_node_details.results | default([]) }}"
  loop_control:
    loop_var: ext_node_item_data
    label: "[{{ ext_node_item.state }}] {{ ext_node_item.name }}"
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

# Set Result

- name: "{{ inner_service_title }} - aws node - set result"
  set_fact:
    cloud_service_result:
      hosts: "{{ ext_node_hosts }}"
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]
