- name: "{{ inner_service_title }} - s3 - vars"
  lrd.ext_cloud.vars:
    identifier: "s3"
    raw_data:
      namespace: "ext_s3"
      state: "{{ inner_service_state }}"
      params: "{{ inner_service_params }}"
      credentials: "{{ inner_service_credentials }}"
      contents: "{{ inner_service_contents }}"
  register: ext_s3_data_wrapper
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ inner_service_title }} - s3 - manage buckets"
  aws_s3:
    s3_url: "{{ ext_s3_item.endpoint | default(omit, true) }}"
    access_key: "{{ ext_s3_item.access_key }}"
    secret_key: "{{ ext_s3_item.secret_key }}"
    bucket: "{{ ext_s3_item.bucket }}"
    permission: "{{ ext_s3_item.permission }}"
    mode: "{{ ext_s3_item.mode }}"
  loop: "{{ ext_s3_data_wrapper.data.list }}"
  loop_control:
    loop_var: ext_s3_item
    label: >-
      [{{ ext_s3_item.mode }}]
      {{ ext_s3_item.bucket }}
      ({{ ext_s3_item.permission }})
  no_log: "{{ env_no_log }}"
