- name: "{{ inner_service_title }} - digital ocean node - vars"
  lrd.ext_cloud.vars:
    identifier: "digital_ocean_node"
    raw_data:
      namespace: "ext_node"
      state: "{{ inner_service_state }}"
      params: "{{ inner_service_params }}"
      credentials: "{{ inner_service_credentials }}"
      contents: "{{ inner_service_contents }}"
  register: ext_node_data_wrapper
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

# Main

- name: "{{ inner_service_title }} - digital ocean node - volumes (create)"
  community.digitalocean.digital_ocean_block_storage:
    command: create
    state: "{{ ext_node_item.state }}"
    oauth_token: "{{ ext_node_data_wrapper.data.oauth_token }}"
    volume_name: "{{ ext_node_item.name }}"
    region: "{{ ext_node_item.region }}"
    block_size: "{{ ext_node_item.block_size }}"
  loop: "{{ ext_node_data_wrapper.data.volumes_to_create }}"
  loop_control:
    loop_var: ext_node_item
    label: "[{{ ext_node_item.state }}]  {{ ext_node_item.name }}"
  no_log: "{{ env_no_log }}"

- name: "{{ inner_service_title }} - digital ocean node - droplets"
  community.digitalocean.digital_ocean_droplet:
    unique_name: true
    name: "{{ ext_node_item.name }}"
    state: "{{ ext_node_item.state }}"
    oauth_token: "{{ ext_node_data_wrapper.data.oauth_token }}"
    region_id: "{{ ext_node_item.region_id }}"
    size_id: "{{ ext_node_item.size_id }}"
    image_id: "{{ ext_node_item.image_id }}"
    wait_timeout: "{{ ext_node_item.wait_timeout }}"
    monitoring: "{{ ext_node_item.monitoring | default(omit, true) }}"
    resize_disk: "{{ ext_node_item.resize_disk | default(omit, true) }}"
    ipv6: "{{ ext_node_item.ipv6 | default(omit, true) }}"
    user_data: "{{ ext_node_item.user_data | default(omit, true) }}"
    private_networking: true
  loop: "{{ ext_node_data_wrapper.data.droplets }}"
  loop_control:
    loop_var: ext_node_item
    label: "[{{ ext_node_item.state }}]  {{ ext_node_item.name }}"
  register: ext_node_details
  no_log: "{{ env_no_log }}"

- name: "{{ inner_service_title }} - digital ocean node - tag the droplets"
  community.digitalocean.digital_ocean_tag:
    api_token: "{{ ext_node_data_wrapper.data.oauth_token }}"
    resource_id: "{{ ext_node_droplet.id }}"
    name: "{{ ext_node_tag }}"
    state: "present"
  vars:
    ext_node_item: "{{ ext_node_item_data.0.ext_node_item }}"
    ext_node_droplet: "{{ ext_node_item_data.0.data.droplet }}"
    ext_node_tag: "{{ ext_node_item_data.1 }}"
  loop: >-
    {{
      (ext_node_details.results | default([]))
      | product(ext_node_data_wrapper.data.tags | default([]))
      | list
    }}
  loop_control:
    loop_var: ext_node_item_data
    label: "{{ ext_node_item.name }} - {{ ext_node_tag }}"
  when: ext_node_item.state == 'present'
  no_log: "{{ env_no_log }}"
  tags: ["no_print_skipped"]

- name: "{{ inner_service_title }} - digital ocean node - volumes (destroy)"
  community.digitalocean.digital_ocean_block_storage:
    command: create
    state: "{{ ext_node_item.state }}"
    oauth_token: "{{ ext_node_data_wrapper.data.oauth_token }}"
    volume_name: "{{ ext_node_item.name }}"
    region: "{{ ext_node_item.region }}"
    block_size: "{{ ext_node_item.block_size }}"
  loop: "{{ ext_node_data_wrapper.data.volumes_to_destroy }}"
  loop_control:
    loop_var: ext_node_item
    label: "[{{ ext_node_item.state }}]  {{ ext_node_item.name }}"
  no_log: "{{ env_no_log }}"

- name: "{{ inner_service_title }} - digital ocean node - set hosts"
  set_fact:
    ext_node_hosts: []
  tags: ["no_print"]

- name: "{{ inner_service_title }} - digital ocean node - set hosts"
  set_fact:
    ext_node_hosts: "{{ ext_node_hosts + [ext_node_item_result] }}"
  vars:
    ext_node_item: "{{ ext_node_item_data.ext_node_item | default({}) }}"
    ext_node_droplet: "{{ ext_node_item_data.data.droplet | default({}) }}"
    ext_node_item_result:
      name: "{{ ext_node_item.name }}"
      state: "{{ ext_node_item.state }}"
      private_ip: >-
        {{
          ext_node_droplet.networks.v4
          | default({})
          | selectattr('type', 'defined')
          | selectattr('type', 'equalto', 'private')
          | selectattr('ip_address', 'defined')
          | map(attribute='ip_address') | list | first | default('')
        }}
      public_ipv4: >-
        {{
          ext_node_droplet.networks.v4
          | default({})
          | selectattr('type', 'defined')
          | selectattr('type', 'equalto', 'public')
          | selectattr('ip_address', 'defined')
          | map(attribute='ip_address') | list | first | default('')
        }}
      public_ipv6: >-
        {{
          ext_node_droplet.networks.v6
          | default({})
          | selectattr('type', 'defined')
          | selectattr('type', 'equalto', 'public')
          | selectattr('ip_address', 'defined')
          | map(attribute='ip_address') | list | first | default('')
        }}
  loop: "{{ ext_node_details.results | default([]) }}"
  loop_control:
    loop_var: ext_node_item_data
    label: "[{{ ext_node_item.state }}]  {{ ext_node_item.name }}"
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

# Set Result

- name: "{{ inner_service_title }} - digital ocean node - set result"
  set_fact:
    cloud_service_result:
      hosts: "{{ ext_node_hosts }}"
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]
