- name: "{{ validator_title }} - aws vpn - validate"
  lrd.ext_cloud.vars:
    identifier: "aws_vpn"
    raw_data:
      state: "present"
      namespace: "ext_vpn"
      params: "{{ validator_item.data.params | default({}) }}"
      credentials: "{{ validator_item.data.credentials | default({}) }}"
      contents: "{{ validator_item.data.contents | default({}) }}"
  no_log: "{{ env_no_log }}"
