### Ensure docker is running and update the docker-compose executable ###

- name: "{{ params.title }} - params"
  set_fact:
    task_params: "{{ tmp_params }}"
    task_compose_params: "{{ tmp_params.compose | default({}) }}"
  vars:
    tmp_params: "{{ params.task.params }}"
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ params.title }} - download the docker compose executable file"
  become: "{{ params.task.root | default(false) }}"
  get_url:
    url: "{{ task_compose_params.src | default(tmp_default_url) }}"
    dest: "{{ task_compose_params.dest | default('/usr/local/bin/docker-compose') }}"
    mode: "{{ task_compose_params.mode | default('755') }}"
  vars:
    tmp_default_url: >-
      https://github.com/docker/compose/releases/download/{{
        task_compose_params.version | default('')
      }}/docker-compose-Linux-x86_64
  when: >-
    ((task_compose_params.src | default('')) != '')
    or
    ((task_compose_params.version | default('')) != '')
  no_log: "{{ env_no_log }}"

- name: "{{ params.title }} - ensure docker is running"
  become: "{{ params.task.root | default(false) }}"
  service:
    name: docker
    state: started
  when: task_params.start_service | default(false) | bool
  no_log: "{{ env_no_log }}"
