- name: "{{ inner_service_title }} - aws cdn (cloudfront) - vars"
  lrd.ext_cloud.vars:
    identifier: "aws_cdn"
    raw_data:
      namespace: "ext_cdn"
      state: "{{ inner_service_state }}"
      params: "{{ inner_service_params }}"
      credentials: "{{ inner_service_credentials }}"
      contents: "{{ inner_service_contents }}"
  register: ext_cdn_data_wrapper
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ inner_service_title }} - aws cdn (cloudfront) - execute"
  community.aws.cloudfront_distribution:
    caller_reference: "{{ ext_cdn_item.name }}"
    state: "{{ ext_cdn_item.state }}"
    access_key: "{{ ext_cdn_item.access_key }}"
    secret_key: "{{ ext_cdn_item.secret_key }}"
    comment: >-
      {{
        ((ext_cdn_item.comment | default('')) == '')
        | ternary(
            ext_cdn_item.name,
            ext_cdn_item.name + ' - ' + (ext_cdn_item.comment | default(''))
          )
      }}
    aliases: "{{ ext_cdn_item.aliases | default(omit) }}"
    cache_behaviors: "{{ ext_cdn_item.cache_behaviors | default(omit) }}"
    custom_error_responses: "{{ ext_cdn_item.custom_error_responses | default(omit) }}"
    default_cache_behavior: "{{ ext_cdn_item.default_cache_behavior | default(omit) }}"
    default_origin_path: "{{ ext_cdn_item.default_origin_path | default(omit) }}"
    default_root_object: "{{ ext_cdn_item.default_root_object | default(omit) }}"
    e_tag: "{{ ext_cdn_item.e_tag | default(omit) }}"
    enabled: "{{ ext_cdn_item.enabled | default(omit) }}"
    http_version: "{{ ext_cdn_item.http_version | default(omit) }}"
    ipv6_enabled: "{{ ext_cdn_item.ipv6_enabled | default(omit) }}"
    logging: "{{ ext_cdn_item.logging | default(omit) }}"
    origins: "{{ ext_cdn_item.origins | default(omit) }}"
    price_class: "{{ ext_cdn_item.price_class | default(omit) }}"
    purge_aliases: true
    purge_cache_behaviors: true
    purge_custom_error_responses: true
    purge_origins: true
    purge_tags: true
    region: "{{ ext_cdn_item.region | default(omit) }}"
    restrictions: "{{ ext_cdn_item.restrictions | default(omit) }}"
    tags: "{{ ext_cdn_item.tags | default(omit) }}"
    validate_certs: "{{ ext_cdn_item.validate_certs | default(omit) }}"
    wait: "{{ ext_cdn_item.wait | default(omit) }}"
    wait_timeout: "{{ ext_cdn_item.wait_timeout | default(omit) }}"
    web_acl_id: "{{ ext_cdn_item.web_acl_id | default(omit) }}"
  loop: "{{ ext_cdn_data_wrapper.data.list }}"
  loop_control:
    loop_var: ext_cdn_item
    label: "[{{ ext_cdn_item.state }}] {{ ext_cdn_item.name }}"
  no_log: "{{ env_no_log }}"
