- name: "{{ inner_service_title }} - aws cdn (cloudfront) - vars"
  lrd.ext_cloud.vars:
    identifier: "aws_cdn"
    raw_data:
      namespace: "ext_cdn"
      state: "{{ inner_service_state }}"
      params: "{{ inner_service_params }}"
      credentials: "{{ inner_service_credentials }}"
      contents: "{{ inner_service_contents }}"
  register: ext_cdn_data_wrapper
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ inner_service_title }} - aws cdn (cloudfront) - execute"
  include_tasks: "aws.item.cdn.yml"
  loop: "{{ ext_cdn_data_wrapper.data.list }}"
  loop_control:
    loop_var: ext_cdn_item
    label: "[{{ ext_cdn_item.state }}] {{ ext_cdn_item.name }}"
  no_log: "{{ env_no_log }}"
