- name: "{{ inner_service_title }} - fastly cdn - vars"
  lrd.ext_cloud.vars:
    identifier: "fastly_cdn"
    raw_data:
      namespace: "ext_cdn"
      state: "{{ inner_service_state }}"
      params: "{{ inner_service_params }}"
      credentials: "{{ inner_service_credentials }}"
      contents: "{{ inner_service_contents }}"
  register: ext_cdn_data_wrapper
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ inner_service_title }} - fastly cdn - execute"
  lrd.ext_cloud.fastly_cdn:
    fastly_api_key: "{{ ext_cdn_item.api_key }}"
    name: "{{ ext_cdn_item.name }}"
    state: "{{ ext_cdn_item.state }}"
    domains: "{{ ext_cdn_item.domains }}"
    activate_new_version: "{{ ext_cdn_item.activate_new_version | default(omit, true) }}"
    healthchecks: "{{ ext_cdn_item.healthchecks | default(omit, true) }}"
    backends: "{{ ext_cdn_item.backends | default(omit, true) }}"
    cache_settings: "{{ ext_cdn_item.cache_settings | default(omit, true) }}"
    conditions: "{{ ext_cdn_item.conditions | default(omit, true) }}"
    directors: "{{ ext_cdn_item.directors | default(omit, true) }}"
    gzips: "{{ ext_cdn_item.gzips | default(omit, true) }}"
    headers: "{{ ext_cdn_item.headers | default(omit, true) }}"
    request_settings: "{{ ext_cdn_item.request_settings | default(omit, true) }}"
    response_objects: "{{ ext_cdn_item.response_objects | default(omit, true) }}"
    snippets: "{{ ext_cdn_item.snippets | default(omit, true) }}"
    s3s: "{{ ext_cdn_item.s3s | default(omit, true) }}"
    syslogs: "{{ ext_cdn_item.syslogs | default(omit, true) }}"
    settings: "{{ ext_cdn_item.settings | default(omit, true) }}"
  loop: "{{ ext_cdn_data_wrapper.data.list }}"
  loop_control:
    loop_var: ext_cdn_item
    label: "[{{ ext_cdn_item.state }}] {{ ext_cdn_item.name }}"
  no_log: "{{ env_no_log }}"
