- name: "{{ inner_service_title }} - aws snapshot - vars"
  lrd.ext_cloud.vars:
    identifier: "aws_snapshot"
    raw_data:
      namespace: "ext_snapshot"
      state: "{{ inner_service_state }}"
      params: "{{ inner_service_params }}"
      credentials: "{{ inner_service_credentials }}"
      contents: "{{ inner_service_contents }}"
  register: ext_snapshot_data_wrapper
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ inner_service_title }} - aws snapshot - execute"
  include_tasks: "aws.item.snapshot.yml"
  loop: "{{ ext_snapshot_data_wrapper.data.list }}"
  loop_control:
    loop_var: ext_snapshot_item
    label: "[{{ ext_snapshot_item.state }}] {{ ext_snapshot_item.name }}"
  no_log: "{{ env_no_log }}"
