- name: "{{ inner_service_title }} - aws elasticsearch - vars"
  lrd.ext_cloud.vars:
    identifier: "aws_elasticsearch"
    raw_data:
      namespace: "ext_elasticsearch"
      state: "{{ inner_service_state }}"
      params: "{{ inner_service_params }}"
      credentials: "{{ inner_service_credentials }}"
      contents: "{{ inner_service_contents }}"
  register: ext_elasticsearch_data_wrapper
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ inner_service_title }} - aws elasticsearch - execute (outer task)"
  include_tasks: "aws.item.elasticsearch.yml"
  loop: "{{ ext_elasticsearch_data_wrapper.data.list }}"
  loop_control:
    loop_var: ext_elasticsearch_item
    label: "[{{ ext_elasticsearch_item.state }}] {{ ext_elasticsearch_item.name }}"
  no_log: "{{ env_no_log }}"
