root: "elasticsearch_schema"
schemas:
  elasticsearch_schema:
    type: "dict"
    description: "Schema for the aws elasticsearch task."
    props:
      namespace:
        type: "str"
        non_empty: true
        choices: ["ext_elasticsearch"]
      params:
        schema: "params"
        non_empty: true
        description: "Parameters for the aws elasticsearch task."
      credentials:
        schema: "credentials"
        non_empty: true
        description: "Credentials for the aws elasticsearch task."
      contents:
        schema: "contents"
        description: "Contents for the aws elasticsearch task."
  params:
    type: "dict"
    description: "godaddy nameserver parameters schema"
    props:
      list:
        type: "list"
        elem_schema: "list_item_params"
        description: "List of elasticsearch services to be created or destroyed."
      absent:
        type: "bool"
        description: "When true, destroy the service instead of creating it."
      name:
        type: "str"
        non_empty: true
        description: "Cluster name to be used."
      region:
        type: "str"
        non_empty: true
        description: "The AWS region to use."
      elasticsearch_version:
        type: "str"
        description: "Elasticsearch version to deploy. Default is '2.3'."
      instance_type:
        type: "str"
        description: "Type of the instances to use for the cluster."
      instance_count:
        type: "int"
        description: "Number of instances for the cluster."
      dedicated_master:
        type: "bool"
        description: "A boolean value to indicate whether a dedicated master node is enabled."
      zone_awareness:
        type: "bool"
        description: "A boolean value to indicate whether zone awareness is enabled."
      dedicated_master_instance_type:
        type: "str"
        description: "The instance type for a dedicated master node."
      dedicated_master_instance_count:
        type: "int"
        description: "Total number of dedicated master nodes, active and on standby, for the cluster."
      ebs:
        type: "bool"
        description: "Specifies whether EBS-based storage is enabled."
      volume_type:
        type: "str"
        description: "Specifies the volume type for EBS-based storage."
      volume_size:
        type: "int"
        description: "Integer to specify the size of an EBS volume."
      vpc_name:
        type: "str"
        description: "Specifies the vpc name associated to the subnets and/or security groups for this domain."
      vpc_subnets:
        type: "list"
        elem_type: "str"
        description: "Specifies the subnet names for VPC endpoint. The property vpc_name must be defined."
      vpc_security_groups:
        type: "list"
        elem_type: "str"
        description: "Specifies the security group names for VPC endpoint. The property vpc_name must be defined."
      snapshot_hour:
        type: "int"
        description: "Integer value from 0 to 23 specifying when the service takes a daily automated snapshot of the specified Elasticsearch domain."
      access_policies:
        type: "dict"
        description: "IAM access policy as a JSON-formatted string."
      wait:
        type: "bool"
        description: "Whether to wait for the cluster to be available. Defaults to true."
      wait_timeout:
        type: "int"
        description: "When wait is true, specifies how much time (in seconds) will wait at most. Defaults to 120 seconds."
  list_item_params:
    type: "dict"
    description: "godaddy nameserver parameters list schema"
    props:
      when:
        type: "bool"
        description: "when false, ignores the item; defaults to true"
      absent:
        type: "bool"
        description: "When true, destroy the service instead of creating it."
      name:
        type: "str"
        non_empty: true
        description: "Cluster name to be used."
      region:
        type: "str"
        non_empty: true
        description: "The AWS region to use."
      elasticsearch_version:
        type: "str"
        description: "Elasticsearch version to deploy. Default is '2.3'."
      instance_type:
        type: "str"
        description: "Type of the instances to use for the cluster."
      instance_count:
        type: "int"
        description: "Number of instances for the cluster."
      zone_awareness:
        type: "bool"
        description: "A boolean value to indicate whether zone awareness is enabled."
      dedicated_master:
        type: "bool"
        description: "A boolean value to indicate whether a dedicated master node is enabled."
      dedicated_master_instance_type:
        type: "str"
        description: "The instance type for a dedicated master node."
      dedicated_master_instance_count:
        type: "int"
        description: "Total number of dedicated master nodes, active and on standby, for the cluster."
      ebs:
        type: "bool"
        description: "Specifies whether EBS-based storage is enabled."
      volume_type:
        type: "str"
        description: "Specifies the volume type for EBS-based storage."
      volume_size:
        type: "int"
        description: "Integer to specify the size of an EBS volume."
      vpc_name:
        type: "str"
        description: "Specifies the vpc name associated to the subnets and/or security groups for this domain."
      vpc_subnets:
        type: "list"
        elem_type: "str"
        description: "Specifies the subnet names for VPC endpoint. The property vpc_name must be defined."
      vpc_security_groups:
        type: "list"
        elem_type: "str"
        description: "Specifies the security group names for VPC endpoint. The property vpc_name must be defined."
      snapshot_hour:
        type: "int"
        description: "Integer value from 0 to 23 specifying when the service takes a daily automated snapshot of the specified Elasticsearch domain."
      access_policies:
        type: "dict"
        description: "IAM access policy as a JSON-formatted string."
      wait:
        type: "bool"
        description: "Whether to wait for the cluster to be available."
      wait_timeout:
        type: "int"
        description: "When wait is true, specifies how much time (in seconds) will wait at most. Defaults to 120 seconds."
  credentials:
    type: "dict"
    description: "AWS elasticsearch credentials schema."
    props:
      elasticsearch:
        schema: "aws_credentials"
        non_empty: true
        description: "AWS elasticsearch main credentials."
  aws_credentials:
    type: "dict"
    description: "AWS elasticsearch main credentials schema."
    props:
      access_key:
        type: "str"
        non_empty: true
        description: "AWS access key."
      secret_key:
        type: "str"
        non_empty: true
        description: "AWS secret key."
