- name: "{{ inner_service_title }} - aws db (rds) - vars"
  lrd.ext_cloud.vars:
    identifier: "aws_db"
    raw_data:
      namespace: "ext_db"
      state: "{{ inner_service_state }}"
      params: "{{ inner_service_params }}"
      credentials: "{{ inner_service_credentials }}"
      contents: "{{ inner_service_contents }}"
  register: ext_db_data_wrapper
  no_log: "{{ env_no_log }}"
  tags: ["no_print"]

- name: "{{ inner_service_title }} - aws db (rds) - create cluster(s)"
  community.aws.rds_cluster:
    state: "present"
    db_cluster_identifier: "{{ ext_db_item.cluster }}"
    access_key: "{{ ext_db_item.access_key }}"
    secret_key: "{{ ext_db_item.secret_key }}"
    region: "{{ ext_db_item.region | default(omit) }}"
    engine: "{{ ext_db_item.engine | default(omit) }}"
    master_username: "{{ ext_db_item.master_username | default(omit) }}"
    master_user_password: "{{ ext_db_item.master_user_password | default(omit) }}"
    tags:
      Name: "cluster-{{ ext_db_item.cluster }}"
  loop: "{{ ext_db_data_wrapper.data.list }}"
  loop_control:
    loop_var: ext_db_item
    label: "{{ ext_db_item.cluster | default('---') }} <{{ ext_db_item.name }}>"
  when: >-
    (ext_db_item.state == 'present')
    and
    ((ext_db_item.cluster | default('')) != '')
    and
    (ext_db_item.own_cluster | default(false) | bool)
  no_log: "{{ env_no_log }}"

- name: "{{ inner_service_title }} - aws db (rds) - execute (outer task)"
  include_tasks: "aws.item.db.yml"
  loop: "{{ ext_db_data_wrapper.data.list }}"
  loop_control:
    loop_var: ext_db_item
    label: "[{{ ext_db_item.state }}] {{ ext_db_item.name }}"
  no_log: "{{ env_no_log }}"

- name: "{{ inner_service_title }} - aws db (rds) - delete cluster(s)"
  community.aws.rds_cluster:
    state: "absent"
    db_cluster_identifier: "{{ ext_db_item.cluster }}"
    access_key: "{{ ext_db_item.access_key }}"
    secret_key: "{{ ext_db_item.secret_key }}"
    region: "{{ ext_db_item.region | default(omit) }}"
    skip_final_snapshot: "{{ ext_db_item.skip_final_snapshot | default(omit) }}"
    final_snapshot_identifier: "{{ ext_db_item.final_snapshot_identifier | default(omit) }}"
  loop: "{{ ext_db_data_wrapper.data.list }}"
  loop_control:
    loop_var: ext_db_item
    label: "{{ ext_db_item.cluster | default('---') }} <{{ ext_db_item.name }}>"
  when: >-
    (ext_db_item.state != 'present')
    and
    ((ext_db_item.cluster | default('')) != '')
    and
    (ext_db_item.own_cluster | default(false) | bool)
  no_log: "{{ env_no_log }}"
